apiVersion: v1
kind: PersistentVolume
metadata:
  name: bulk-minio-0
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: bulk-hdd
  local:
    path: /data/k8s/minio-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - omkarhomelabnewpc
