---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ssg-studentsystemgo-app
  namespace: studentsystemgo
spec:
  encryptedData:
    db-password: AgCBIQTcjNZKxfafIQJitBDFx2DJ7NN8U/dKdkoIqNlFb/tZ/8In+kJlOP9AGQTgtrRoeNhfnOU/T1/cRnxDr1xkw22hyYh0oXrCTGcTGV8co/7Q6MQHEjiil178P2cYfsMDXOVGKqfc7LpUNCHNSoyCWyRU4wXYNIPL4dCm6NChJXfYrsm8rnmMfSZXrpLTA/idauT1n6ZqVPBnLIndPOAix2nsBIc/dbBGCaQQeGGMNeX9IjhLDvHPQiB9LHpfukYaZTVQvPN05Gtxvzr4tfXFoW3+5hM/tHcYi+XXLXvEQmFqIzxeulT7KvwRa2psDs86vUVEpSie3Vyqdcp6X/S2nBofD8p5d9IYwuU6HYNoeFJTbQhAEDBgHD4T8wl5kMxz/VUM2W8u9ltcBixIP+c6/HGVjpBGaQnkLvBb6Cqx2r9nsYFClqeuUh9FByukAul2or4yRdeszDPzOuNWukZQGNLZnejr8TANYq8FVFL1NfRsrFsl0S6A2w2pnh9xxbr+sGIbG6qi9IUFuUyiKQSMPtlVUm/EHbs5QBqXGA2fS4iHPoXV3CBaYcoc61GBUnQE+HHAQ414UVp4A2MOBUq5MtsAZMwlkH9bTjVaV8UnGRn9fEabTMy4PnQkQpipzO38kj3CvPeaW4GsPMGz39JJ17ctBb9zoAjaFdVCmYB7Od4Ov3lQ0fngFIByMujS+OHRZF7VqJuZ/hI=
    jwt-secret: AgAwzU+7LLHLjkVzNFiCTRr7ynOy/Flb7vPi6Z6ZYUVPWbMBZL0Lw2+viXMZYzUZ44nA0FNKxI+4IxMCd6rgcviad2RyivNYUAGQJT280yeG2IwW2a047h4ey6Dzjv8bD1beWr1uB7zlgyv0ux8d98wFakUcrTwSd3lFEw7HxbKp/zaEDQLaXvRylNk5xuJjamx/EzfPyoxJZ/YPPbYTedegCRx61rAYequCItMt+IWOAfA3+XFYZc3qllJxcsXIEV/g5WRDrSQk5CmXjR2UwCAD4y5ueGBeuwIdqnr3g8G6Jy6E9XZWMamLNVp+jKhR8qZ7109Hv8C+QFeOBybPj60rF2gObAY4FAZA00zJzctOQSsNoujqf15BunstRyjErZizg8EHaN6HoUepJlCmuzfPeic0mm0Jp3FZDk8IkF9WEBIRTK5yk5ZcqwK/Z/bPApVAouhQpKyfG9ku+7H4yx3Wjw3l1YjpKcLdfMjI3uBHa37HVXDmNRotyR5kHaydyrHhx0HKb3Lmk7dG9BPkTOI9qx6FmX4Dhd3+YZ9rkd9VzA4gpA4LSxf/pFoKGxE+iEtbFRh0ur8Uc4oyZGOFfMbdU4DuSJEikRufPxBBPsC3porakqxBJPUTsY9WUQN1JZRIS8KtV6EgOusqNMqrcvbil/2ckQ8Vvp5EdTLsZj5Ra17q6tZ8Bo5e3heLU1n8Aa8mMSR1SZMgFaiAcHNawTTppTjbqsinUnX+hwCxk/iK
  template:
    metadata:
      name: ssg-studentsystemgo-app
      namespace: studentsystemgo
    type: Opaque
