---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ssg-studentsystemgo-mysql
  namespace: studentsystemgo
spec:
  encryptedData:
    replication-password: AgA1b7iyMMSV9q+2aAAyMJewIdWPExA3GBqqfd/1T0vr3uc92MrLDtGLrB3OKkIRwEC9iAmHCISrIJ6va4Vsu9qfJnVXDGowUzGWwGqxnsOBhHbjLpvKlxT+VFXb97I7jEE7dOLmK+8SDivGQJW7uJueMqqa/iqlaY9qXR8yxy5pBAjCUaKQXk4lo28UQO+EkJL8R1ZL034xIXP1Gy/EKQxGqa4EGrGxD028mrj04xvoUyKRaqPf6LSCydlVHeng1Wo5Talm2P+BhwFEIdUTxiv3n6gRfLSvsprmmUyCxlmPwR8DKULUArMYAMFbP5Il3QA6Py+mxYmRWPWBkt8A2ZOkrSvTKyL+cRslRJyYpjlPmNxDSzG6cyXg79XurSQYwZTiyMoBeCAtuPct+xDFRRcFFc/IjCQs22+m69P+M740Kyz+RdJlpvuDzLyyh1yVJN/Te9Q4WlI2+TSLe0u7hqH46Po1zo7Dhp7TT8C+C68lCWm4nli3UhgXfHg/GYuy8sypz8zFFpWMjj5cJGTlhxBWsUPICqfiFN889iEYeM7Ekv5b+dMJH6ktIoVP8ORca5BlaKvoW8Xm9a+N1D1TP1OmI57MCW6TdEw40iPgKoI0Ltwwk69En0jGWSebhpPXGmFplvVN3va5/tcJjyfV30dmEVdydV1IDi580dBv1xkkazYr49jCPSaQeAgdutCTSAXhI/IatemwVkCNsA==
    root-password: AgAT0ntK16Le0q5m9ftPG9H8+iJKsbZU7NXiCedD2Fiu0EdIA/YOVuR+WGUb9IHhPt0pVnToIu4kpLug0ze9Ntmx1+SN75fUsCoTpvSLNljtC77KS0wUPM7/VhtOZlG9rZXVH0InfQARclN1+ThkBZTGUWzZOvejTR3iRRLyO4/d4RFZaGiEN8r2xmGi7KDVKC3Hn5+/x2S4fD/l+m9VC17tHLzcpR9PgFefEhQVMPkjjR3RQxNYfBpIbh2QHNGDsAeXZCZZRQ5BZ53tN7kOaaDmiNQkpXeQwQ6LndgU1kpRwE9crOuCpsDYaEv/2kTEdtGsxtfsR1Q61DID6WEwWqCIrprXAzwmPaIvYR+VFbByazHrUXVwkF7sfQwCLEhYsTAoWXsfXf9etZd6ZOH7nCObuXrV3tEF1Ct8vmSfqNeqLsbgVtRQ3EvfGLXsp+pOiwRed2ifMbIXJ5xMdcXeUh+p73XwSel890tKYIJLDNSwoJCXOxkzXbIk6ibwHHnFwXrqKqeYMDtPLEtN9CHdSV1KD8HV0cblHJl3I4/+pqAfprxdtwboHpDFgBOpyMkUBed+Iwh+6JkbNXU6nk+gm77zSkvG0GYkQXFn8clPI2dnTY7elk6fBLlizZfen5TwGa93tve50/6H9wNRdqiJezA+UpagqU+e0xeXIV0/ccxqKayKpyQkcmI+Wd4qsmdGarrIEfoSNsEjLzo=
  template:
    metadata:
      name: ssg-studentsystemgo-mysql
      namespace: studentsystemgo
    type: Opaque
