---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-backup
  namespace: uptime-kuma
spec:
  encryptedData:
    accessKey: AgAQekFbYjB2RRm7xwh96zZV/FQx4zP+wJEydojUpqY55ARXWd966ytZ7qTk/5CtMOMbcZPYUENhGdlRyNm+V+0OIN/susgQsdls/Fkj3wEwzGZGoMF1T2gx3SSF5wQapyQjwgv/9YB+pEoaddTrJEm8O6TgOTiUTYMG3Jzgect3OqRkncQSLZzbjzhstQGwDrUVBy29k6EQZKVFSN2Lpt0jSesGfu4HUEzU4KZBgObg0iUWfMb/asOwDyw6Drujz0wyHboEf6xbMpLiTn7+ZkOSen/77qx7UlyhxTJCCB6e97Mc57M3rE6lGZ9XCfSQPgF0HrVYgvMe+/lriXI1cNaxWZA97lIifsIMUyHxljg771NV9sHvwjMSMUXU1kZZB0rfPjn/3ZWHWWVLiXFXQFzyXUPcVPsH5GYi63lVrHTjuexFvJTmpu5Jnkc4qwreLlzEThPO1VptnhmEb0UfROA93qy49aZ9v7HcJiyhxDhWrPAgNaU/v2h7R9D7JWCeZVaOR6gB2ti2SLbenm4PycDmcL6dornreO7Mh6njwm5mC0tK00i2gYWOSVqj8gUx3+31FUCy2UaItKKvg5NfPYSA4ZykcEJ0EZYV0YtazQWBAHK/ne4JEI+TfjxBSNqmm7wXLgFJXGMlmoENJKLCaeXyKiHz3A53d0J1VkotHRRYCAlABEKGIAG3l0NE3uXUol624nQHb1eswd4zxHZs
    secretKey: AgASzRSq568/kgB0D+s1zo7cn0VRGTNAE1vJ64vVvS/XdbIegnkMjtWAmEYE0QJrSt7Y3IuhPFusbLV6sEFXN/3VzY549I/D7JCr5h95yJpxOtUKGY9Hvf+0rpQC0GTNR7/sOgWcwsIJmU8hwvvuEWy6LS11HPjsZaxCwN8t/+dfOszavjofSNFx+I1B1iYxSvJ8GfCeubwq2hworvNwR7QK8mwGmaZR6QkL8l8r8LPDd99WrmSh3yE0bfj3ZR54OaZAuNxdGI/CWbKcxssqBaRPX7N/BpWV2zQmdSh8/rUy3GFsedGiNhUugPC7cYVylOWf/pqstbcO43QYRg9vuhu+HFpGyzj9NKrh8RxmfvguC+RDKe5/cmasO8JIRh/YhCZMD5CjCGVLcVm6HLu1z1cLzWKt3gkA03DeibIi+7cYwPlp5QqhE4BNxEkfblr80yPA8N698NV++7sIJh8lGzg9UaNefxuo4/J+ckgjF5he+ufyla0ssxtNp9CMyOGKoaA5Zo/cgNBfWLy6ScbHceX8uXcOtMPSFS/LWqaE8/mLaiL5MWjbFQlVHcm2rBm+XoY1eyS2yVk1+edax+v8tUTaMkdvZe2gvhZzpajcvyi5vBkKhY+ysjgAA7ld5b/1rZe/bsNNwkpXfqTdf4XhSQChOr1Eb8H6la4VYE/7EyZU8UDlt6oJUS/Hx82EJTMD/hQepiYB/7eJREM=
  template:
    metadata:
      name: minio-backup
      namespace: uptime-kuma
