---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-backup
  namespace: uptime-kuma
spec:
  encryptedData:
    accessKey: AgB7i4sZWK9TunYfMU5iV3PrWww2NFZzO7+gdxKxiW7VxC9v7nPcV5xVczQtzLI59MmM82Gml8WNLbtxtRPBs96ZDGYmuIun11tLeRbKzoX4ZaM+UdvUZVIvc+GD/lAGya5bS6Ku6XEkyFr1c9l2XGRuXUwo8Ez8R+vX0D4P9hLpbh2+IWA+QZaVLqfJjdaUnOl6DzsdsFZobyZMNxTp8PmoVkvqRNsk/ToZFXy0rCS8nG5aMXLuQw613x/nZkIk4vLi2pFPD4kSHCDIjKlVxqcZjSWied7OtV/n7QizNKtOl0EXmzTdFZfOGuWmnnPC7VtvDq4Dzloy4vP0UGK/1vSfR7ExdPsmhRi7Fx+XCTFnP/0C7i/9/uNroKk1zvn9wIMLZmbpu5n1XIZpfRdUP0RnL0VWq54MLafTX+2E7JOdFQSXleHaJeimY4VOQ3zKFhRoWpj6Fe0aqpvi4eGFF//G7AGOqTB3fbIBpnMAlsEuIzkgH06bHYOtoBQWAXKAkB9fJ9foqAIT9Q3rigAAk8SKxqSsxPPantSNMxj/Pe/RXVJkB6FqPm2jujDlmB+CKh5fxEKxU2mto9MmLv9cLNFni9pWdTUWGHT0PFLufFBNqGlsyt42HZuF282zIVughsz59zY47jesMiofNqNeUgjjNJgnRL6Jb5GJ3hOQiB7W49Gto3vdZll4VKvMb8B5raEJflQoTn1+gXrCKDgx
    secretKey: AgBVc3NRzqgfEuwYTMnVeZJ01cy9C/3NoR7vMed1orAYGoil2wYEz/t5SLhKzfBafF7y6kAGtF36sf1ml6whVExA4ALyP818UikoTYKApOYGIfiNaAuScrHQXdq9AN8M+1kdWxLw2YGFzltVW9rEwuUdVcPFDbBa/TtriyI0HI3EXTf7BJxcMesjb/rnsrrBekUodtTcjw8QgqWKWvEQ7J+frMCCCLMvY0TM+jl2cGoa8oK+5OKl1Qx+DVQWUu7gQd0C3CElIpwSVCmIV0zHU1/s1Ud8kEN8yVR31UBM4/4oqZ3chUmf2/h6zeJ/3QouVI7WLDK5JePwFR4VLUdHFkzRJU4Dx9P1v3qgVvNbZbu3JqkwiUh1nH9bRLvbtB3ZVdrBVWUTM7TZv7RB6O/6m425IiE1lC5pCclTHEBrnNnMbNJNC6lvUj68a26ssFIIv2iEky1tbzYUAMtVmZRdzX7SqxRyv4Y9U1+h3SI2jeq18RRcfAU4iMaIEGff68/KIqnmsEQ+Nw/jWyBN5keNyr1Jfz5HvsnruzFTIkucxpN7pvrXuUfnGmin3ewFr3ktY9mNOZGmqqnFa0YQx+8lK/cO+xU3DBFp1xXwqVL7lVdaxwOWMJPIcnp//v2t7ZSJldF72d5eY63Wg7rtYCgy4Q37wNkgfEepPT8qfxRBQv8b/31eYoZhb0khryb9d0eJ54F8Buhfnlh4FNgkd0MrYgCZkr08WQTZ5Eej
  template:
    metadata:
      name: minio-backup
      namespace: uptime-kuma
