---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-backup
  namespace: newsfeed
spec:
  encryptedData:
    accessKey: AgCHGn/hUVwWUVm9Peg2CQNWDXA0CyGEm0oILoN/T+zEwHARgtrW3+F0G27qcak/E/HtJ8cW/X+F/DUxndWL/bf6rOAvvKle8HKoOf2nad9PEa04nZXSLsHfraPG47lLJyL3dW0GLq+QQOxp4QMK5IZxZ+RpD+TZQPm/Gup69HMxhP8iLwlgjv64eQ71PjSXer6fpE33o9M4/aMBorgXX3MOye00ksDyPO7eIHWC1web8lgFPd4xWc7sutNUxSCrBHc3Dja764vC2tfoxx2Ju3rJ+V7m1FFkwxDvkat33FeqXT5Q0gRRP4hNTxeuOxFOTzQNPwuTq4cK3X5LEEuF8LnSRZHGaLsl8F1NFiTJQ7R/UhG4raS801fdjq+fCEHjkGyAEe8Wf5hrFciG1afjFtDBVNTJgVqj8l/DOh1gVA3dZdy1RN2dXdeyr58ctVGnx5NrOd6o5Fy5H8vHFJkdjfutXcSF4+8aoING2+yPQyYrhULCRIv7aeuc4krb6R6LTfB6GgP515+vtwtLe4hpXnRIm6ciCisVD7e/lNHOIz60SgWGvLbpaDnOdfQic7bQJAAls5stsCIW1Z/e2ogz7qPu9s+3UmkUqHlGoMwzPYYBCg0yGHbXLoBnrY1o9k/eP5LCdC/gAW4SlcEUI3z59hkeM9ZBezQGv0IWWSzPjIWnDLMgTiVm0dbf/yNheHjX6NMnmagnK+31OtwyfFZ9
    secretKey: AgArzAwfUWOKxxE6qmsrnHJySV1y+dZ3VVJdhlM3kSgS4pw00XjZrTf14g7TtqvybLD6BweeLC8Ekfc/KwgChGYW4ZvLrM82x2Jk+QWrIt+TeJjr6oMJkkw+YFAaHM6JsDi2iGnKq751veaT9HjwgTTbSG4sQ0Avewa21WPYxihA/aE2BeYf6m8iSNK6Evl5MerRdTKFIzACJSs7fZOwTxTZrkvgnjzfyQ9kioWfCMTXlBn0UqbxfPCCewddOnTvOh3R7PBhVbethlSKGfqYrpym5HFQdu61jYpywpUnixowO3Z5Dz5cs6/tZUmSdQtYEnrN+qRg+iyYsaJ5IHG0k6tO36gz6xNioF2d2VLgHSkMLxMvzst+Bq9G/67/uEFRb5klDE2OxVgCFbYGX+8LUZKFcWfsLhJjEYI31dv8gxOfvnQGs3vIA7XBmP2Jhye3hmjylGe+YmyFbRn8rrK9OyomrR/IuvRJ6Pq0fh774ZbMuOrqe2mIzLY9ojEyVUlwVGjqinGdmdagdp3kQvLlnzHi2bsW5r1LgHs3CLtDp5Zr8+vVpZ1eSdXFURmnautKu31iX4gHQabj0GohmgnDie/kyg3KWYvqeonC55OSp7+FNTMq0odq6Z/qFBkOe5+SNrsARqNeBmtKUSKHYysBb+t6B4OIJE0do3jeMF8DVxL0tPpKNkCw5t9C+PVr4gAlBRUsxF9f3YBrXC4=
  template:
    metadata:
      name: minio-backup
      namespace: newsfeed
