---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-backup
  namespace: uptime-kuma
spec:
  encryptedData:
    accessKey: AgBZZBDmrj/v+0v5xHOvNaLj9x07woY7lgu9jv2km4paPdj4L4o+C6V+7pSzcZG++AISMpEkPJJr0/rGBwKD2kbf+6+7rI83ZC+XTVE89NHnhrBtdg3VrBa7xJsyeoOqsXIikJ0Nwv+lav/zB9mlFwVwwK0wOPmxPQTrpHJlwOjTN/1kwhyllzkKEc4FhI3n1vmFhiRwwG2yNjXcYeJfpt8BJd7KmrSuk0+SbHz1UPL5kE2PpS7IqMKCRBrWHHhCrW7yS7RRQYkCFo1ksicjDJF/ej1ZgkfcTO6ldL+CI064/vJMM6mPma8lhIzteaAjvww6m8k/SCDGwpH0olE1UVraYMmx3INfo6bJD9/qHBgiYH0nCPcbYN0tsvEHkVtXb42woq7d+KEkI+3H1Djk5xqkFKkr+vktIkOD/vgepn4VDFXnPRNX06HQqMkj+mtnTb1pOMzSwCfWuutzCQz0mAcRx8UBxS9TEDSTOQ9Dt8Px9PQSL5Gql2ZZJTfH5LH2JGZOlxhe8/wl4zRxxB6qfdXeksQRuWRjTdpgIi+kx84dlURml7ycOH9UXbj8xxvf3gBDWEp8t53BxRbq51KUrgOgqTgOoRaM5c2kquMPvaSQrHzRU4yKYShQNMpjwY7izKRAFaJXHmTPTjcV3FS8SAG3s/Zk2tHyaDKNp8jFE0nGzYXMBfUaRjzP+XYfqfqpA1SgCYkJI381KhMtzj4T
    secretKey: AgCHjpVm9K4sEsGaZXObLLUjsHpKLq02YaJxHILbZlrDXbH5IquMeQfMF9wBNgLK8yyNXZC4Ndjw075+muNFDQtdSTium318wrjTzaU29H7WxbD93Ycludp43+s8h6mStT0oYTTyJYoyMK4CF4BC+I0/P8Fb6YHRfhFDvWqzdA3RidgxXOtI83QTATXDhwxdZd9mfTc/Rd4dEEdhHmSnbtB+HIbbQNnUEHXesh+Tmp1cW4lhI73DfMzohgM7o+dWyqfh6RMh7rm0cyOt/fviLo3Xg1oWeHJ8UlRS1M11w/AebbHTpaylH2jW3Ic2ykwogt0aNr0VwQiIfkIRj/mnGlk3ybMmB88VhRIZL1SxrYyxyZjQHH0EY2B+SpRVKpCn5YGrAMGnYfD8w5O2tlpLokYTcc1eJmp/fUTwIJTN+CBkLo6dPO2k5ZcGWWn0COsLsbtNZyyJit2iF+OuG+2javKsmKvLuYgCsxF16OEf2L5aA7LkpBICASVwT+zpztwphEg0i5FHmnxoWXOSx0j4oxvvgxg5vRvbJ85AsTX1H0hhGQEoa4hX4sDU4y3x+4w4GgTFDHuIWm/JmiDTI9vXCwbEvi9nxi1So5rcWONNfqxT8Zzwy2Jm1/1Tilh58wsRv0qAdQoST9YkzYFDngTN0cgARavffF0Z2prI7t0KWkgrq0UwB4Xi9Jep6eeGJ7msl3g+RqBtXEiV0Fw=
  template:
    metadata:
      name: minio-backup
      namespace: uptime-kuma
