---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgCBxgRirXVD9mqhkvqJigDtmP7K9LV6gzC9ci5HZQaZdRyG3uAZ84u3wAieBFDF5FN+FJzuNXXS97gf7bo/Irv0xt4EjzRZZBI5+kYunFNr6YRTdYHi46+QATTGrwVAlJt0aiWexss8SyawaVkYJWO4PlfhAGPAjDIhLI+nWkpYjzr4xffqptpgK2h4oSsvMVys8TDjSr7HH66B15ui42YHfImLeGAGaif7r7QqgKhqeyA6cy0t57LTdMLwT0n9CEZiYYi2Ppaot/uMDw2CU72glhbXFFU23MRfzO+omiwDq9u7GiyH/YDpjvAby2apZXvYPOfWNvnntpQGLNNgbx4lp/TB5EAjj5TEu/IoAMHBoXuA8smz04lnGPj5DaAZrLVzJhYEHRJIFEIVnkZhQV/OeXWEghRkMFV/+0ya1pE6tPInvdIo/h0RKv4ymsEL46iNvjl94h9ujI3Q4VCuj42p8FGEt7D/f+91r1zRSvokP42xVFs9l3RQqnQExT+E6svcNI5nzEju3LLPsET85DAZh6knSaKBRLzSqQOwUWY0CneyjwrY70QJoFUJXz/uNBhL78ydVUJeYjB9jdTSeZdW+fNDPKbZeRBIjKMB0/4K5G7pjVRyeNFkhdxtWPyKCNljYQj066ml+rRYgWJz8lU4iLBx3a9ZEtvty17FALI+lV3c9+dtDHb3DtuTyfeDU0Nkeb7wBTdkhmvsFrEziVzRfHCRmeGd
    rootUser: AgAVexSVfSh23iyVxrR8KzaGg0/1AJa6Aw7N1S9U+5RQjQ7dlY3I7rRfwwTwJinwkolyeBGruya2FWI6tXYjMV8hDMHZ4X8HvtuXWuGTrHD79DXuSoEDaO9PIDp8OjoMm9ME3/n47dMcMbCFO5QhtWCWveCgtTdeeN8baIpYLduQlC00NhgQDxkrOVAW1Nh2+d9VZQe9K6whj6q3puW0gEaySBKY3uenJrxiM9Cdx4KFzD+y1ZB/g55ce4rfyufYuOkeTndvFJ3LBfgooFCKaMp7W7ZFlpMhMl9U3s6SDSwG631812Fl8mg98WvWHrCPfew8rcfqJCJ2YPcx+Cvm4BeLcZ8trTwM3cWaljuAKuUqyTdH8shOCOpNgepf374Rve/epNhycequ2D6xPRIloY1hteoo4ovDT4xu4HDSQBT/n1qVKqalbSQuuYQH4y6oAd2yXqr7P2wo6O2j55R857UmiyjtanQHfK5txu6RiAGTSmUOqdTdVz620+YIe+hdVdhpd5siig/tg5qomq7w1aR5th9N0EF6kurIT8+cLcmjhkGgpnigho2BM8Y4S8yo6xTqRuSdXHzvQDnK8MJ6lanIlHgFKzmc1iYWEx4Ckyn4IIQO3LG0uFvuzkxhQwmHtr8ZP4iIM9NaY1mDppR6SziFUDmcovyi8O/6aAQzNuLacC02lBbfvQBzM+E+cFeW5weZF7/AxTx07V2E
  template:
    metadata:
      name: minio-root
      namespace: minio
