---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgBFesGrSnLXlXC++yk+plwS7/8Qegfo4m6cXBOPn/lzppLA7/9vI45WhJhfV8e9xUjVWcJqVd2ZSEhyZMenLaHNkd7QSsTPXm/OLmp2DgRLxVEkl+Gsdcr8AEsal6H0yvKnG4qDgLBfbDoEhcW/3SzDX5seY2spxO1M+PPwDMdT19vilNOhB7uz9rykRScnmy7rp9qqunhEyjCIx+KFYQNy657FcuEtNprkoG1jYXDeZVJAhaQYRXipVpVeJb7bNPkhQs0RPlxq9pO0K+lAkNmd982TyA76Ax1pPbhXVzpFRcl6tPUixeYvWHiDUGaM5MG8rdUHOS3bN27My8hclxURczMrD5Ju8dvjm+VNOmavT1lHtqf2ZE8svRNdOf0k9pj9ZHvwizpNQjrf46sWipmigG0Uau0GTBTU0+QO/b2DkW3agPWBTIMACuPzstXNFvQmbVe2GrNu4QS0ZLZbo/Ifrl5EOK5HXsieVMuLEt9140onglo9/WYbwnwRtPdrTHeEAX1DUULgGv/lazs5dYYAG70CfldIW38w8z3xQXXEJIIWWedblQX7FXjU4s4cfjxoLS+Pa2PCfMFUHSQOIgte9iZTFP5v34STUynvBLpu70zhz40izuENaTtba1ap5Be4QkouMJjGk9nfqPsMxDto4YGFzp8DvHhCtfO2LXHdAmNUKta+PqQHNtjQGIqVIbNq/ikGWUkKxmM=
    rootUser: AgAl9oL+ItwVZJAzeopf3zRBkSKsryuGerBpE3JIoPWlWreTTC9MZfasV73LgK2GCNdwA9mwaWQhMEJcWqMaDzHKEDAC7QEchj1M3TL0Q5AaKzieBF0FVFY7WbdXO+D2Cy2Ft7C/SD0KVMsHAPZY5hM+S0uyUCXucNFhpLVFCtOS5175zO5xtk8XD5WZcbWbb9nhvJVXmdRYPlusEiEbEmJT0zKSnEycTuBVemT9oJIvZPqkMx/ahNkcA++CMITP6CNOEFOdU6nzRkbo2ILY8DzTiTH1z2j0LzUAQjCr9EZzdTYkb7H3ryhV7prEpJsIY49kJehsVPYXFOjFhhkKGqTQ1F1GcZxEOFx4Dx1oTPzhhQ0yp2td0hmHuWRPu9CncT4NxqttkYb8KK6/JjraUsjGhtPW52gs9S4yf+FKXjtr/d+DIHFcVMJQXUW1lRhBH3fC6+oaJNJnlF5jJDdUVJvM+OUOEYUUV70s1Q1ywaip5ovmLOdyYx72hyjJiAnnxlT91so+lwWSqSkMaV3+3HHewxtzxl3rP45Djn/HVUwzJi8k3qoGHdIrXlJSHwMH+L2UKs2NYMQpuIpX31AI0MqU9RWcBJkPjQV4XECtP5YNNsGlSb7Oe5I8dO/5l39DRHWb4qy8tXtc22j/E7pgj2MlAsXi/yY3GtKOKj3fw/mOjKD/c8lDCIeX4g2uWNp8oAHBVegYWWVLJ2jyqw0w
  template:
    metadata:
      name: minio-root
      namespace: minio
